# Generated by Django 4.0.3 on 2022-03-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
