# Generated by Django 4.0.3 on 2022-03-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order2', '0004_alter_orderdetail_cuantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data_time',
            field=models.DateTimeField(),
        ),
    ]
